### PR TITLE
Fix discord crash when use ShowHiddenChannels plugin

### PR DESCRIPTION
**Pull request by book777**
https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/ShowHiddenChannels/ShowHiddenChannels.plugin.js

### CODE REVIEW

**Comment by Farcrada** [comment]
Did you check if version 4.0.1 works? Because if that one works I'm curious to see what your console returns.

**Comment by book777** [comment]
Discord was crashed on 4.0.1 for me

**Comment by Farcrada** [comment]
What does the console say?

**Comment by book777** [comment]
That the channel in getPermissionsOfChannel is undefined

**Comment by Farcrada** [comment]
Right, Have you tried 4.0.1? I uploaded it just before you made the pull request: https://github.com/Farcrada/DiscordPlugins/commit/fe0a2a8cc346ae870737f0c8d41d45c87d13585b 4.0.1: https://github.com/Farcrada/DiscordPlugins/blob/master/Channel-Permissions/ChannelPermissions.plugin.js

Let me know if that solves the issue as well, or if you run into other issues.

**Comment by book777** [comment]
No, the fe0a2a8 is still crashes

**Comment by book777** [comment]
image

**Comment by book777** [comment]
image

**Comment by Farcrada** [comment]
Can you see what `parent_id` is on your line: 502? I'm wondering why it fails this check:
```
if (!channel.parent_id) <--
	return { topic: channel.topic };
```

**Comment by book777** [comment]
image

**Comment by Farcrada** [comment]
There we have our issue! Thank you very much!

**Comment by book777** [comment]
`			//Check if the channel is part of a category
			if (!channel.parent_id)
				//if not, simply return with a topic
				return { topic: channel.topic };

			const parentChannel = this.getChannel(channel.parent_id);
			if (!parentChannel)
				return { topic: channel.topic };

			const parentPerms = this.getPermissionsOfChannel(parentChannel),
				channelPerms = this.getPermissionsOfChannel(channel);

			//Return with topic and sync property
			return { topic: channel.topic, categorySynced: JSON.stringify(parentPerms) === JSON.stringify(channelPerms) };
		}`
		
works fine for me

**Comment by Farcrada** [comment]
Let me know if that fixes it for you as well!

**Comment by book777** [comment]
Your solution didn't helps 
image

**Comment by Farcrada** [comment]
It doesn't work when you hover over channels? Or just there in the console?

**Comment by Farcrada** [comment]
You can @ me in the BetterDiscord server so communications will go a bit smoother, if you want.

**Pull request closed without merging**
